### ISSUE TITLE
Request for example repo or gist

### ISSUE THREAD

**Issue by jamesdeantv** [PriceFallin/cordova-plugin-twilio-video#1]
Hi there Prince.  I arrived from the thread https://github.com/twilio/twilio-video.js/issues/85

First, thanks for supplying the repo.  Could you possibly provide an example repo of the plugin in a basic ionic app setup using the twilio  programmable video sdk.  The latest version as of this issue is "twilio-video": "1.5.0"  I've tried implementing the plugin, but Im having trouble registering it in a page.  It isn't explicitly stated how to declare the plugin.  

For example:
`
declare const TwilioVideoPlugin;
`
`
declare const VideoConversationPlugin;
`
`
declare const cordova.videoconversation;
`
`
declare const cordova-plugin-twilio-video;
`
`
import * as ? from ?;
`

You stated in the readme to 
`
Get token And Call the API cordova.videoconversation.open( RoomName: string, Token: string);
`

So, do you mean to first request the token from the server and then run
`
cordova.videoconversation.connect( RoomName: string, Token: string)
`

I ask this because the latest twilio video api doesn't contain a method or global called open.

Even a single gist showing the plugin being declared and then called in the export class would suffice.  

Thanks again.

**Comment by PriceFallin** [comment]
I'm assuming you're referencing an Ionic 2/3 app.

I was able to successfully implement this in an Ionic v1 app, but haven't implemented it in Ionic 2/3 yet. I do plan on doing that soon though. Also, this plugin is built for both version so I would imagine it would work.

Try declaring 'cordova' in the head of the source file where you want to use the plugin. You might have to rename it to something else like 'cordova-video-call' throughout the plugin (ex. cordova-video-call.videoconversation.open...). You can just declare it with:
`declare var cordova: any` 

or if you change the name:
`declare var cordova-video-call : any`

The `open` command is just the function name we decided to use in the javascript that connects to the native code.

I don't have an example just yet but when I finally get this working in my Ionic3 app I'll try to send some more info if you're still having trouble. Hopefully this is helpful for you.

-Price

**Comment by smuaq** [comment]
Thanks for supplying the repo @PriceFallin ! I've been using my own improved implementation of opentok plugin for video chats for over a year now. Would you be able to supply a sample running app (ionic 1) I would love to do a performance/usability test for twilio vs opentok. Thanks again!

**Comment by jamesdeantv** [comment]
I was able to successfully get up and running with the help of your repo.  Thanks!

**Comment by PriceFallin** [comment]
Hi @smuaq, I don't have a demo set up that I can provide. For this you'll need to just build your own, although all you really should need is a simple button that would call the cordova function to start the video chat. Of course you would also need to either set up your own server to get a token/roomID or generate one from Twilio's video tool console.

@jamesdeantv Glad you got it working!

**Comment by smuaq** [comment]
Great thanks!

**Comment by WisaniShilumani** [comment]
@jamesdeantv mind sharing your code?

**Comment by PriceFallin** [comment]
@WisaniShilumani I actually started working on an ionic3 app now with the plugin and was able to get it working with my new build.

Here's some tips:
- Before you install the plugin, put it in a directory in your project. For example, I put mine in `/plugin-src`. Then when you're ready to install run `ionic cordova plugin install /path/to/plugin --nofetch` (the no fetch flag basically let's ionic know that there is no npm registry for the plugin.
- Declare cordova in the class file that you want to use it in: `declare const cordova: any;`. This will expose cordova and the attached `videoconversation` methods to it so that you can call it by using `cordova.videoconversation.open(...)`. I have my plugin named different so if `cordova` doesn't work then you can rename it throughout the plugin as I mentioned earlier in this thread.

Hope this helps!

**Comment by WisaniShilumani** [comment]
@PriceFallin Thanks a million! That's super helpful. I managed with the typescript work, but later ran into problems with cordova 7. It didn't like the hyphens in the AndroidManifest.xml file during the build. The `android:name="cordova-plugin-twilio-video.ConversationActivity"` in particular.

I replaced all hyphens with points, and it's working fine now. Thanks for the plugin, been struggling with video calling for over 3 months now!

**Comment by jamesdeantv** [comment]
Glad to hear you got things sorted.

**Comment by dzungcao** [comment]
Hi everyone, I am a bit new to Ionic, I am now trying to use @PriceFallin's code in my Ionic 3 project but I am not sure what to do in the step:

**Declare app name the head of source file where you want to use the plugin (ionic 2/3 only)**

Can anyone tell me what I should do in this step?

**Comment by dzungcao** [comment]
Hi @WisaniShilumani, would you mind to share with me how you did the change on hyphens ?

Thank you very much.

**Comment by cavalryjim** [comment]
@WisaniShilumani or @dzungcao, can you share the solution to the hyphens error?  I have the plugin working with iOS and recently added the Android platform to my project.  When trying to build, I receive:
```
AndroidManifest.xml:68: Tag <activity> attribute name has invalid character '-'.
```

Thanks!

**Comment by WisaniShilumani** [comment]
@cavalryjim No need to uninstall. Replace hyphens with points at both platform and plugin level. I did a search & find and made the changes at both levels. I recently made a switch to WebRTC and don't have a record of the changes, sorry about that.

**Comment by cavalryjim** [comment]
Posting this only to help anyone experiencing the '-' hyphen issue...
I created a renamed version that works with:
```
$ java -version
java version "1.8.0_131"
$ npm --version
5.7.1
$ ionic --version
3.20.0
$ cordova --version
7.1.0
```
https://github.com/cavalryjim/videoCordovaPluginTwilioVideo
